name: sekigae
title: 席替え侍
base: core18
version: "1.0"
issues: https://github.com/sis314/sekigae/issues
source-code: https://github.com/sis314/sekigae.git
website: https://mican3.github.io/sekigae.html
summary: 席替えアプリ
description: Flutterベースのデスクトップ用『席替えアプリ』
type: app
confinement: strict
license: GPL-3.0+
grade: stable
architectures:
  - amd64
apps:
  sekigae:
    command: bin/sekigae
    extensions: [flutter-stable]
    plugs:
      - home
parts:
  sekigae:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
  # ファイルピッカーを開くため
  # Integrate custom dialogs in your snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/integrate-custom-dialogs-in-your-snap/10825
  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration

